version: '3.4'

# This config is for development purposes only


volumes:
  pip_cache:
  virtual_environment:
  postgres:

services:
  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_PASSWORD=dj_pass123
      - POSTGRES_USER=dj_user
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf:ro
  redis:
    image: redis
    ports:
      - "6379:6379"
